name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26

    - name: Build server
      run: bash server-build.sh

    - name: Build batch
      run: bash batch-build.sh

    - name: Test
      run: go test -v ./...

    - name: Create Release and Upload Binaries
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        make_latest: true
        files: |
               batch
               server
